services:
    app:
        build:
          context: ./
          dockerfile: app-blog/scripts/docker/Dockerfile-app
        ports:
            - "5250:5250"

networks:
  default:
    external:
      name: test-network
