FROM openjdk:17.0.2-jdk-buster

RUN apt-get update && apt-get install -y \
  wget \
  sudo

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN sudo apt install -y ./google-chrome-stable_current_amd64.deb
